version: "3"

services:
  node:
    container_name: "download-file-server"
    build: ./node/
    ports:
      - "5000:5000"
    links:
      - redis
    depends_on:
      - redis
    environment:
      - REDIS_PORT=6379
      - REDIS_HOST=redis
      - SERVER_PORT=5000
      - SERVER_HOST=0.0.0.0
    networks:
      - app-network

  redis:
    image: redis:6.0-rc4
    networks:
      - app-network
    restart: always

  prometheus:
    container_name: "prometheus"
    image: prom/prometheus:v2.17.2
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus-data/:/etc/prometheus/
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    links:
      - node:node
    networks:
      - app-network
    restart: always

  grafana:
    container_name: "grafana"
    image: grafana/grafana::6.7.3
    depends_on:
      - prometheus
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
    networks:
      - app-network
    restart: always

volumes:
  prometheus_data: {}
  grafana_data: {}

networks:
  app-network:
    driver: bridge
